version: "3.9"

services:
  preprocess:
    image: preprocess:1.0
    volumes: 
      - shared_dir:/data

  models:
    depends_on: 
      - preprocess
    image: model:1.0
    volumes: 
      - shared_dir:/data

  prediction:
    depends_on: 
      - preprocess
      - models
    image: pred:1.0
    volumes: 
      - shared_dir:/data

volumes:
  shared_dir:
 
  



